### ISSUE TITLE
Got an update today and now can't use the extension.

### ISSUE THREAD

**Issue by da0ist** [elvetemedve/gnome-shell-extension-system-monitor#47]
System:    Host: X250 Kernel: 4.4.0-112-generic x86_64 (64 bit)
           Desktop: Gnome 3.18.5 Distro: Ubuntu 16.04 xenial

**Comment by elvetemedve** [comment]
I think that's because Gnome 3.18 can't interpret the new Javascript syntax introduced in Gnome 3.26.
I don't know about any tool that could check the backward compatibility of an extension, so I haven't removed the compatibility for older versions yet.

Release 11 is deactivated now, so it won't be offered as an update any more. I'll create a version 12 which will be marked as incompatible with old Gnome versions.

What you can do is to go to the [release page](https://github.com/elvetemedve/gnome-shell-extension-system-monitor/releases) and download the previous release which is version 10. After that extract the ZIP into the `~/.local/share/gnome-shell/extensions/System_Monitor@bghome.gmail.com/` directory.

**Comment by elvetemedve** [comment]
Fixed in version 12.
