### ISSUE TITLE
Doesn't work on UbuntuiGNOME 16.04 with GNOME 3.20

### ISSUE THREAD

**Issue by cdysthe** [elvetemedve/gnome-shell-extension-system-monitor#5]
The extension won't install and run on UbuntuGNOME 16.04 with GNOME 3.20. The slider on the extension page just jumps back to 'Off' as soon as I try tro install it.

**Comment by elvetemedve** [comment]
Hi @cdysthe,

Have you checked that the package **libgtop-2.0-10** is installed?

In the Gnome desktop session press `Alt + F2` and type the `lg` command. Now select the **Extensions** tab on the top right corner. Scroll down to the _System Monitor_ entry and click on the **Show Errors** label.
Do you see any errors there?

**Comment by jbicha** [comment]
`sudo apt install gir1.2-gtop-2.0`

Please add that note to the extension install page since that package is required for Debian and Ubuntu but nothing depends on it (meaning it won't otherwise be installed) and as far as I know, there's  not an easy way for an extension to automatically install dependencies like that unless the extension itself is packaged in the repositories.

**Comment by elvetemedve** [comment]
@jbicha Thanks for the correct package name. :+1: 
I've updated the description here https://extensions.gnome.org/extension/1064/system-monitor/

@cdysthe Please install the package mentioned above and check if the extension installs without an issue.

**Comment by HarlemSquirrel** [comment]
I can confirm that installing `gir1.2-gtop-2.0` and then reloading GNOME with Alt + F2 and `R` works for me.

**Comment by elvetemedve** [comment]
Thanks @HarlemSquirrel.
