### ISSUE TITLE
statvfs journal spam

### ISSUE THREAD

**Issue by ilyazzz** [elvetemedve/gnome-shell-extension-system-monitor#71]
I'm using gnome-shell 3.38.2 on fedora 33, and the extension causes lots of spam in the journal (this message appears every 2 seconds):
`gnome-shell[2816]: glibtop(c=2816): [WARNING] statvfs '/var/lib/containers/storage/overlay' failed: Permission denied`
I assume this is from the storage usage analyzer. Disabling the disk indicator stops the spam.

**Comment by elvetemedve** [comment]
Hi @ilyazzz,

Actually it's not the extension itself, but one of its dependencies [libgtop](https://gitlab.gnome.org/GNOME/libgtop) emitted that error. To calculate disk usage `libgtop` scans all the mount points in the filesystem, however the directory `/var/lib/containers/storage/overlay` is not readable by the user of the gnome shell.
This problem is [already reported](https://gitlab.gnome.org/GNOME/libgtop/-/issues/42) upstream.
